### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by MrJonsenPrivacy** [libracore/WooCommerceConnector#31] opened 2020-08-15 18:13 UTC
Hi,

I am getting this error when i trying to save my settings in WoocommerceConnector:

Traceback (most recent call last):
  File "/home/erpnext/erpnext/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/erpnext/erpnext/apps/frappe/frappe/model/document.py", line 266, in save
    return self._save(*args, **kwargs)
  File "/home/erpnext/erpnext/apps/frappe/frappe/model/document.py", line 302, in _save
    self.run_before_save_methods()
  File "/home/erpnext/erpnext/apps/frappe/frappe/model/document.py", line 881, in run_before_save_methods
    self.run_method("validate")
  File "/home/erpnext/erpnext/apps/frappe/frappe/model/document.py", line 781, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/erpnext/erpnext/apps/frappe/frappe/model/document.py", line 1051, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/erpnext/erpnext/apps/frappe/frappe/model/document.py", line 1034, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/erpnext/erpnext/apps/frappe/frappe/model/document.py", line 775, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/erpnext/erpnext/apps/woocommerceconnector/woocommerceconnector/woocommerceconnector/doctype/woocommerce_config/woocommerce_config.py", line 17, in validate
    self.validate_access()
  File "/home/erpnext/erpnext/apps/woocommerceconnector/woocommerceconnector/woocommerceconnector/doctype/woocommerce_config/woocommerce_config.py", line 27, in validate_access
    "api_secret": self.get_password(fieldname='api_secret',raise_exception=False), "woocommerce_url": self.woocommerce_url, "verify_ssl": self.verify_ssl})
  File "/home/erpnext/erpnext/apps/woocommerceconnector/woocommerceconnector/woocommerce_requests.py", line 61, in get_request
    return get_request_request(path, settings).json()
  File "/home/erpnext/erpnext/apps/woocommerceconnector/woocommerceconnector/woocommerce_requests.py", line 55, in get_request_request
    message="{0}: {1}".format(r.url, r.json()),
  File "/home/erpnext/erpnext/env/local/lib/python2.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Can anybody help me? I use ERPNext v12.

best regards

**Comment by lasalesi** [comment] 2020-08-19 12:56
Do you have an API key and secret provided? You can get these from your WooCommerce instance under WooCommerce > Settings > Extended > Rest API

Without these values, the connection cannot be validated...

**Comment by lasalesi** [comment] 2020-08-21 06:55
Possible duplicate of #30.

Make sure that REST API is available (by default not the case) under Settings > Permalinks

**Closed by lasalesi** 2020-08-21 06:55 UTC
