### ISSUE TITLE
Non stock items sync issue

### ISSUE THREAD

**Issue by ribikkhoteja** [libracore/WooCommerceConnector#63] opened 2022-08-19 12:57 UTC
I cannot sync non stock items. Can you please check the link below for the solution ?
I want non stock items to sync from erp to woocommerce.

https://github.com/libracore/WooCommerceConnector/issues/58

**Comment by lasalesi** [comment] 2022-08-22 08:20
Duplicate of #58

**Closed by lasalesi** 2022-08-22 08:20 UTC
