### ISSUE TITLE
Sales orders are not sysnc

### ISSUE THREAD

**Issue by sanath2021** [libracore/WooCommerceConnector#39] opened 2021-01-12 06:58 UTC
Hi,

I have installed and try to get sales orders from WOO, but it import items only.
Here is my setup

![image](https://user-images.githubusercontent.com/77319046/104280028-4b1caa80-54d1-11eb-81a1-ce4c40ccd23b.png)

![image](https://user-images.githubusercontent.com/77319046/104280060-5a035d00-54d1-11eb-9cec-b6f990b69374.png)

![image](https://user-images.githubusercontent.com/77319046/104280092-65568880-54d1-11eb-8865-eb7517cd7e0a.png)

I found something in error log in ERPNEXT

![image](https://user-images.githubusercontent.com/77319046/104280173-815a2a00-54d1-11eb-8ffb-12cbed6bf5a9.png)

Would you help me to work this app and I would like to donate some for your incredible work done.

**Comment by heikkiheer** [comment] 2021-02-06 19:50
I have the same problems

**Comment by doniafrizal** [comment] 2021-02-27 01:19
i also have same problem. i am using v13

**Comment by ascorbic-acid** [comment] 2021-03-19 14:25
you need to share all errors logs from the logs page

**Comment by lasalesi** [comment] 2021-06-03 12:20
This might have been caused by the date filter being applied to sales orders. It has been resolved in 

https://github.com/libracore/WooCommerceConnector/commit/524e2620f3d1dc282f78920815a7c670b522d800

**Closed by lasalesi** 2021-06-03 12:20 UTC
